name: helm-chartsnap-action
description: Snapshot testing tool for Helm chart
author: jlandowner

inputs:
  repo:
    description: URL of the Helm repository
    required: false

  chart:
    description: Name of the Helm chart
    required: true

runs:
  using: composite
  steps:
    - id: setup-helm
      uses: azure/setup-helm@v3

    - id: setup-chartsnap
      run: |
        helm plugin install https://github.com/jlandowner/helm-chartsnap
      shell: bash

    - id: run-chartsnap
      run: |
        if [[ $REPO != "" ]]; then
          helm chartsnap -c $CHART -- --repo $REPO
        else
          helm chartsnap -c $CHART
        fi
      env:
        CHART: ${{ inputs.chart }}
        REPO: ${{ inputs.repo }}
      shell: bash
