name: helm-chartsnap-action
description: Snapshot testing tool for Helm chart
author: jlandowner

inputs:
  repo:
    description: URL of the Helm repository
    required: false

  chart:
    description: Name of the Helm chart
    required: true

  values:
    description: Path to the values file or directroy
    required: false

runs:
  using: composite
  steps:
    - id: setup-helm
      uses: azure/setup-helm@v3

    - id: setup-chartsnap
      run: |
        helm plugin install https://github.com/jlandowner/helm-chartsnap
      shell: bash

    - id: run-chartsnap
      run: |
        [[ -z $VALUES ]] && OPT_VALUES="-f $VALUES"
        [[ -z $REPO ]] && OPT_ADDTIONAL_ARGS="-- --repo $REPO"
        helm chartsnap -c $CHART $OPT_VALUES $OPT_ADDTIONAL_ARGS
      env:
        CHART: ${{ inputs.chart }}
        REPO: ${{ inputs.repo }}
        VALUES: ${{ inputs.values }}
      shell: bash
