name: CI

on: [push]

jobs:
  test_action_remote_create_pr:
    runs-on: ubuntu-latest
    name: Remote chart snapshot and create PR
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Snapshot
        uses: ./
        id: chartsnap
        with:
          chart: ingress-nginx
          repo: https://kubernetes.github.io/ingress-nginx
          values: test/remote/ingress-nginx.values.yaml
          update_snapshot: true

  test_action_local:
    runs-on: ubuntu-latest
    name: Local chart snapshot
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Snapshot
        uses: ./
        id: chartsnap
        with:
          chart: test/app1/
